### ISSUE TITLE
Failing with "invalid credentials to build"

### ISSUE THREAD

**Issue by maeddes** [nrekretep/k8s-dev-cluster#1]
Hi Peter,

I went through your tutorial and I think it is cool :)

I ran into the same issue a you (I think) ... was that the error that you got:

```
Staging app and tracing logs...
   prepare:main.go:83: invalid credentials to build to /70082d7c-4e50-43f6-bac7-62fe580bd97b
Error staging application: Stager error: Kpack build failed. build failure message: ''. err: 'the server could not find the requested resource (get pods 70082d7c-4e50-43f6-bac7-62fe580bd97b-build-1-sq5zl-build-pod)
```

What I found missing in your description is the specification of the app registry. Try to add this at the end of your cf-values yaml (the unrendered one):

```
app_registry:
   hostname: https://index.docker.io/v1/
   repository: "<my_username>"
   username: "<my_username>"
   password: "<my_password>"
```

Let me know how that goes!

**Comment by nrekretep** [comment]
Hi Matthias,
thanks for helping me with this container registry issue. 
It now works like a charm. 

Thanks!
